apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bharata-katha-akv
  namespace: bharata-katha
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""   # Leave empty to use system-assigned managed identity
    keyvaultName: "<YOUR_KEY_VAULT_NAME>"
    tenantId: "<YOUR_TENANT_ID>"
    objects: |
      array:
        - |
          objectName: mysql-host
          objectType: secret
        - |
          objectName: mysql-db-name
          objectType: secret
        - |
          objectName: mysql-admin-password
          objectType: secret
        - |
          objectName: mysql-admin-user
          objectType: secret
  secretObjects:
    - secretName: bharata-katha-secret
      type: Opaque
      data:
        - objectName: mysql-host
          key: MYSQL_HOST
        - objectName: mysql-db-name
          key: MYSQL_DB_NAME
        - objectName: mysql-admin-password
          key: DB_PASSWORD
        - objectName: mysql-admin-user
          key: DB_USER
